name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    steps:
      - uses: actions/checkout@v1
      - name: Using node version ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      -name: yarn install
      run: |
        yarn install
      -name: yarn build
      run: | 
          yarn build 
